### ISSUE TITLE
Pointer to example and doc missing

### ISSUE THREAD

**Issue by zenny** [JimRou/template_kaobook#1]
Bonjour Monsieur @JimRou ,

The pointer to documentation and example in https://github.com/JimRou/template_kaobook/blob/6585ac7ce660a78ed8a24376a54c4dd711fbda9a/README.md?plain=1#L30 is missing, fyi.

Thanks for sharing the repo.

Merçi beaucoup.

Cheers,
@zenny

**Comment by JimRou** [comment]
Thank You Zenny, 
It's fixed
